### ISSUE TITLE
Create an exercise for the `FormBuilder` section

### ISSUE THREAD

**Issue by barretodavid** [rangle/angular-training-slides#104]
Create an exercise for the `FormBuilder` section of the slides.

Additional information:
- [Exercise Guidelines](https://docs.google.com/document/d/1t2rLglPKLPEue-gJ2DAVefglbqr2g2daeHUbzqmWW2o/edit#heading=h.5btd8e1fv1jv)
- [Example exercise](https://github.com/rangle/angular-training-slides/tree/master/exercises/structural-directives)

**Comment by ShaunLloyd** [comment]
I'll take this on :+1:
