### ISSUE TITLE
Create an exercise for Typescript

### ISSUE THREAD

**Issue by ggprod** [rangle/angular-training-slides#119]
We should have an exercise to review Typescript

**Comment by ggprod** [comment]
This is a good exercise, but a little too similar to the ES6 exercise.  We should try to add a bit more Typescript specific content to it, perhaps writing a simple decorator and/or installing and using typings for a popular library (lodash for example) and/or type inference and/or union/intersection types, and/or more content on Interfaces

**Comment by rpdasilva** [comment]
That's a good idea actually - or (maybe more advanced) since we got the questions yesterday, creating/stubbing out typings for libraries that have no available type definitions

**Comment by ShaunLloyd** [comment]
This has already been completed in <a href="https://github.com/rangle/angular-training-slides/pull/127">pull request #127</a>
