### ISSUE TITLE
Create an exercise for RxJS/Observables

### ISSUE THREAD

**Issue by ggprod** [rangle/angular-training-slides#120]

**Comment by sonukapoor** [comment]
@barretodavid @ggprod 
Any objections by anybody if I take this to create the solution and exercise?

**Comment by ggprod** [comment]
as we discussed, go ahead @sonukapoor, thanks!

**Comment by ggprod** [comment]
Exercise is pretty good but there is a little cleanup we could do (there is at least 1 typing error in the solution plunkers) and could use one exercise with scan or reduce
