### ISSUE TITLE
Form-builder exercise re-factor

### ISSUE THREAD

**Issue by ggprod** [rangle/angular-training-slides#133]
Though the exercise is good it could use a bit of refactoring.  Either splitting each form control into separate components and/or else bringing it in line with http://blog.rangle.io/angular-2-ngmodel-and-custom-form-components/

**Comment by sonukapoor** [comment]
@ggprod I can take care of this.

**Comment by ggprod** [comment]
@sonu.. sure that'd be great! please go ahead 😄

**Comment by sonukapoor** [comment]
Any time constraints on this?

**Comment by ggprod** [comment]
No, from my perspective everything is pretty good as-is, the issues I'm logging are all just improvements that are more 'do when someone is free/interested'

**Comment by sonukapoor** [comment]
@ggprod The blog post you pointed out is really good, but I strongly believe that converting our solution to this technique is too advanced. I would keep it simple. Let's discuss this offline after the standup when you have some time.

**Comment by ggprod** [comment]
@sonukapoor  Yes, we can keep it simpler.  How about just breaking each control (along with it's error list) into a separate component?

**Comment by sonukapoor** [comment]
@ggprod Sure, we can do that. I think it makes sense keep the current solution as well. 

1. Current example shows how you can complete the exercise using a single component. 
2. The new example will show you how the same can be achieved using separate components. 

This gives the user the option to see both ways. Most of the users will most likely create the solution  using method 1. What do you think?

**Comment by ggprod** [comment]
@sonukapoor I think it would be better to just have a single exercise with the controls broken into components as that is closer to how model-driven-forms should be used.  The current exercise (with it's large template) doesn't reflect well on how model-driven-forms should be used.

**Comment by sonukapoor** [comment]
@ggprod Sure. Sounds good.
