### ISSUE TITLE
Merge most of the exercises into single cohesive angular-cli project

### ISSUE THREAD

**Issue by ggprod** [rangle/angular-training-slides#134]
In the public training on 2/14-2/15 the participants felt it was a bit tedious to run ng new for each exercise (their windows machines took a while to complete that step).  They suggested to merge the exercises into a single angular-cli project so that that ng new step doesn't need to be repeated each time.  Having the exercises build together would also give them a sense of creating a more significant web-app after completing all the exercises

**Comment by sonukapoor** [comment]
@ggprod I can take care of this.

**Comment by ggprod** [comment]
@sonukapoor sure, but before you start we need to get David's input on this one.

**Comment by sonukapoor** [comment]
@ggprod Sure. Let's discuss on Tuesday.

**Comment by sonukapoor** [comment]
@Card we need to have a discussion about this with @barretodavid before we can proceed.

**Comment by e-schultz** [comment]
angular-cli supports multiple apps now I think - would it be possible to leverage this to have one cli-app with a better skeleton/starting-point for each exercise, so it's just a matter of needing to basically git-clone the app, npm install and go from there?

**Comment by AgentEm** [comment]
@gvwilson is this card still needed/relevant?

**Comment by AgentEm** [comment]
@gvwilson not going to fix
