### ISSUE TITLE
Create slides for Angular 1 to 2+ migration.

### ISSUE THREAD

**Issue by ggprod** [rangle/angular-training-slides#135]
This could cover the same material or a subset from the gitbook

**Comment by sonukapoor** [comment]
This is a very interesting topic that I would like to take on.

**Comment by ggprod** [comment]
@sonukapoor sure, go ahead, you could use material from https://angular-2-training-book.rangle.io/handout/migrate/ and https://angular.io/docs/ts/latest/guide/upgrade.html
