### ISSUE TITLE
Http module plunker has a few errors (https://plnkr.co/edit/E9xJ9nUGxOQ66AbOmGXL?p=preview)

### ISSUE THREAD

**Issue by ggprod** [rangle/angular-training-slides#136]
An html error (unclosed app-user) but even after fixing that it seems there is another problem

**Comment by sonukapoor** [comment]
@ggprod There is no plunker on slide 61. Can you please paste the plnkr link?

**Comment by ggprod** [comment]
@sonukapoor sorry Sonu, I forgot their are different branches with different slide orderings.

The slide is Importing the HttpModule and the link to the plunkr is https://plnkr.co/edit/E9xJ9nUGxOQ66AbOmGXL?p=preview

**Comment by sonukapoor** [comment]
@ggprod What other issues do you see? I fixed the missing unclosed tag in my fork here. Can you review this for the other issues before I submit a PR?

https://plnkr.co/edit/l4n2upSueYw5UbFjZB1C?p=preview

**Comment by ggprod** [comment]
I guess I was mistaken, the unclosed tag was the only problem.  Looks good, thanks!
