### ISSUE TITLE
Create slides for RxJS/Observables

### ISSUE THREAD

**Issue by ggprod** [rangle/angular-training-slides#137]
A few slides on RxJS/Observables would be helfpul.  Can cover a subset or entire gitbook material

**Comment by stevechae** [comment]
Will the slides be focused on RxJS 5 as opposed to RxJS <4?

**Comment by ggprod** [comment]
I think the focus should be on <=4 but you can add a slide or two about 5 if you like

**Comment by rpdasilva** [comment]
@ggprod I think since Angular depends on v5 that's where the focus should be.

We haven't been using <= 4 for a while

https://github.com/angular/angular/blob/master/package.json

**Comment by ggprod** [comment]
ah, yes, I got my versions mixed up, my mistake.. v5 it is
