### ISSUE TITLE
Verify exercise components-in-depth

### ISSUE THREAD

**Issue by sonukapoor** [rangle/angular-training-slides#145]
Verify that the exercise and solution match and that they make sense. 

Try to complete the exercise yourself.
 - Are you able to complete it within 20 minutes?

**Comment by ZhangMYihua** [comment]
- Exercise is very complicated for what the learner understands at this point. Perhaps reducing the amount of work necessary would help in understanding. 
- I have done this exercise 3 times and only on the third time was I able to finish it in the given timeframe of 20 minutes. 
- Required understanding of how to use window.setInterval, what it returns  along with cancelling it. If learners don't know or remember they may have to google how to do it which distracts them from learning the angular lessons at hand.
