### ISSUE TITLE
Verify exercise pipes

### ISSUE THREAD

**Issue by sonukapoor** [rangle/angular-training-slides#148]
Verify that the exercise and solution match and that they make sense. 

Try to complete the exercise yourself.
 - Are you able to complete it within 20 minutes?

**Comment by ZhangMYihua** [comment]
- The last step of the exercise requires some understanding of math to complete which learners may not have. 
- Actual solution of last step is quite complex, requiring understanding of javascript Math object as well as math concepts such as log which is not explained in the slides.

**Comment by sonukapoor** [comment]
@ZhangMYihua Can we take the math examples out and simplify it?

**Comment by ZhangMYihua** [comment]
@sonukapoor I think it would be difficult to remove the last step given the nature of the exercise involves math and exponent natured calculations.

**Comment by sonukapoor** [comment]
@ZhangMYihua Ok. In that case I think we will need to refactor the entire exercise to simplify it. Let's keep this card open for now please.

**Comment by ZhangMYihua** [comment]
@sonukapoor Another option could be to provide them with the function and they can just implement it in the pipe.

**Comment by sonukapoor** [comment]
@ZhangMYihua That's a good idea. @tsungting What do you think?
