### ISSUE TITLE
Verify exercise routing

### ISSUE THREAD

**Issue by sonukapoor** [rangle/angular-training-slides#149]
Verify that the exercise and solution match and that they make sense. 

Try to complete the exercise yourself.
 - Are you able to complete it within 20 minutes?

**Comment by jhnching** [comment]
- Exercise is slightly long for 20 minutes.
- Consider putting a reminder in step 7 to add UsersService into the providers array in app.module.ts

**Comment by sonukapoor** [comment]
@jhnching I think we intentionally do not want to put a reminder into the exercise about adding the service into the provider. We want the user to see the error and then add it. There is also a warning when you generate a service using the cli that service is not provided. 

@tsungting What are your thoughts?

**Comment by tsungting** [comment]
I was thinking that the exercises should be as barebones as possible so the instructor(s) at the time can have the flexibility to get the student to do additional things unique to the class.  Such things may be:

1.  extension on questions asked
2.  tasks relevant to the project client has in mind
3.  room for students to come up with their own tasks
4.  time for questions

Maybe consider removing the services for the routing exercise (?)
