### ISSUE TITLE
Verify structural-directives

### ISSUE THREAD

**Issue by sonukapoor** [rangle/angular-training-slides#150]
Verify that the exercise and solution match and that they make sense. 

Try to complete the exercise yourself.
 - Are you able to complete it within 20 minutes?

**Comment by ShaunLloyd** [comment]
@sonukapoor This can easily be done in 20 minutes however there are some issues with the exercise.

1. It has the student constantly rewrite templates to show that the application works throughout

2. Asks student to add buttons to filter laptop collection but doesn't explicitly talk about how the app will filter the data

**Comment by sonukapoor** [comment]
@ShaunLloyd 

1. Can we include part of a bare `HTML` template (without angular specific code) into the exercise for them to copy paste?

2. Can we add necessary steps in the exercise to explain how to filter?
