### ISSUE TITLE
Refactor exercise es6

### ISSUE THREAD

**Issue by ZhangMYihua** [rangle/angular-training-slides#163]
I was able to complete the exercise within the given time, however there are two features used in the solution that is not mentioned in the slides. Promises and Promise.race().

**Comment by ZhangMYihua** [comment]
Was able to finish the exercise in 20 minutes, but parts were a bit complex like onError function in the http-client service.

We should say where the imports are regarding the path for some of the Angular features. Ex. Remind users in the instructions that Response comes from '@angular/http' and which path of rxjs the operators map and catch are from.

The implementation of onError is a little complex in the solution, learners may not know the return of the error object so perhaps instructions should tell them to log the error object and which properties to display.

**Comment by stevechae** [comment]
In addition to talking about `Promise.race()`, the current solutions for ES6 exercises do not really use any other ES6 construct. This should be updated as well.
