### ISSUE TITLE
Refactor exercise Http-Service

### ISSUE THREAD

**Issue by ZhangMYihua** [rangle/angular-training-slides#165]
Was able to finish the exercise in 20 minutes, but parts were a bit complex like onError function in the http-client service.

We should say where the imports are regarding the path for some of the Angular features. Ex. Remind users in the instructions that Response comes from '@angular/http' and which path of rxjs the operators map and catch are from.

The implementation of onError is a little complex in the solution, learners may not know the return of the error object so perhaps instructions should tell them to log the error object and which properties to display.

**Comment by e-schultz** [comment]
I think maybe just a console.log on the error then Observable.throw it, and explain 'this is how you can capture errors for logging/whatever, but still pass them down to be handled in other parts of your application'
