### ISSUE TITLE
Components In Depth Exercise: Investigate Unit Test as Instruction

### ISSUE THREAD

**Issue by tsungting** [rangle/angular-training-slides#177]
Investigate how hard is it to use unit tests as instructions for this exercises by trying to write some unit tests.

**Comment by jhnching** [comment]
I've refactored the exercise to use test cases, which took a couple hours to do. Most of the time was used to ramp up with Jasmine and converting the easier exercises should not be a difficult task. However, for this exercise I see a few complications:
- errors returned from the test may not be very intuitive for the student
- some scenarios are fairly difficult to mock
- all the errors are shown at one time, there is no way to stop the test execution on the first error
