### ISSUE TITLE
Typescript Exercise : Investigate Unit Test as Instruction

### ISSUE THREAD

**Issue by tsungting** [rangle/angular-training-slides#180]
Investigate how hard is it to use unit tests as instructions for this exercises by trying to write some unit tests.

**Comment by stevechae** [comment]
Work on this is also being covered in #181 as there is a lot of overlap between TypeScript and ES6 (TypeScript is a superset of ES6).

**Comment by gvwilson** [comment]
Recommend putting this on hold for now since @stevechae's experience shows that unit test infrastructure will be a distraction for early-stage exercises.
