### ISSUE TITLE
ES6 : Investigate Unit Test as Instruction

### ISSUE THREAD

**Issue by tsungting** [rangle/angular-training-slides#181]
Investigate how hard is it to use unit tests as instructions for this exercises by trying to write some unit tests.

**Comment by stevechae** [comment]
I'm finding there's a lot of overlap between ES6 and TypeScript. 

This is even more complicated by the fact `angular-cli` generates an Angular 2 project in TypeScript only.

It might be wise to merge ES6 exercise with TypeScript exercises if we intend to use Unit Tests approach to exercises.

**Comment by gvwilson** [comment]
I agree with Steve's assesment:
1. We shouldn't introduce ES6-in-pure-Javascript, we should introduce these features using Typescript types right from the start.
2. Angular's testing framework probably isn't the right tool to use for intro-to-language unit tests - we want something much simpler (Jest? Mocha?) that is designed for using in batch mode on the command line.
Recommendation:
1. Steve will see if Mocha can be used with Typescript.
2. Steve will park this one for now and switch to exploring unit tests for teaching Typescript.

**Comment by stevechae** [comment]
So far I've had some success with setting up TypeScript with Mocha. One concern that I have; however, is the fact that Mocha isn't exactly the same thing as Jasmine, which is used as the default option for Angular 2. I'm not sure if this would cause confusion among students when they finally get to the Unit Testing phase of the training.

**Comment by stevechae** [comment]
Had a talk with @tsungting . One approach we could take is to create exercises in the context of Angular, but only cover features that are often used while working with an Angular 2 project and omit the others (such as inheritance or promises).  But this means we would need to introduce the students to at least basic Angular constructs such as Components, Modules etc. 

We also agree that ES6 exercises can be merged into TypeScript exercises as Angular 2 code is most often written in TypeScript.

**Comment by stevechae** [comment]
I will attempt to create a small set of unit test cases for TypeScript using Mocha and see how it looks.
