### ISSUE TITLE
Inaccuracy (and typo) in services section

### ISSUE THREAD

**Issue by rpdasilva** [rangle/angular-training-slides#211]
> Services need to be register in a module

Should be `registered`

Content should be revised unless we're holding back on talking about the injector tree for simplicity's sake. Services don't _need_ to be registered in the module. The `providers` array simply instantiates them. Services registered at the module level are simply made available application-wide.  A service can be instantiated at the `@Component`, `@Directive`, or `@Pipe` level inside of their own respective `providers` arrays. This is how we can achieve separate instances of the same service, or only expose a service to a certain subset/branch of our application hierarchy.

**Comment by gvwilson** [comment]
Closed by 376fd73
