### ISSUE TITLE
How can I create a component that supports two-way data binding?

### ISSUE THREAD

**Issue by rpdasilva** [rangle/angular-training-slides#257]
- Two-way data binding is a combination of `@Input` and `@Output`
 - `@Output` name should be the same as `@Input` with an added `Change` suffix
 - `<foo [(data)]="parentData">` is equivalent to `<foo [data]="parentData" (dataChange)="parentData = $event">`

Q: What is the shorthand form of `<counter [count]="parentCount" (countChange)="parentCount = $event">`
A: `<counter [(count)]="parentCount>`

20min

**Comment by gvwilson** [comment]
Closed in favor of #256.
