### ISSUE TITLE
Update Forms Slide Content

### ISSUE THREAD

**Issue by sonukapoor** [rangle/angular-training-slides#283]
- [x] How do I create forms in Angular (10 min)
  - Import FormsModule
  - Use NgModel
- [x] How do I handle forms data (10 min)
  - Using component members (ngModel)
  - Using ngForm directive
- [x] How do I handle form submission (15 min)
  - Event binding (submit, ngForm, ngSubmit)
- [x] How do I validate my form (10 min)
  - Template validators
- [x] How do I display error messages (15 min)
  - Using form validation state i.e: `myForm.errors.required`
- [ ] Can I create custom validators (15 min)
  - Create a custom validator
- [x] Can I change the look of my form based on validation (10 min)
  - Using validation classes i.e: `.ng-dirty`
- [x] Can I bind a form to a model instead of using a template (25 min)
  - Import ReactiveFormsModule
  - Inject / configure FormBuilder
- [x] How do validate my form model (15 min)
  - Validators in FormBuilder
- [x] How can I logically separate different sections of a form (10 min)
  - use FormGroups
- [x] How can I dynamically generate form fields (10 min)
  - FormBuilder
  - FormArray
  - Template-driven (ngFor / ngIf)

Total ~2 hours

**Comment by sonukapoor** [comment]
@rpdasilva I discussed the custom validators topic for template forms with @jamesbs and we both that this section is probably out of scope for the training, since it requires creating custom directives for template forms. Let us know what you think about this. Also @jamesbs will be completing the dynamic forms section. 

@gvwilson FYI

**Comment by gvwilson** [comment]
Part of #289.
