### ISSUE TITLE
Update Testing Slides

### ISSUE THREAD

**Issue by mdegani** [rangle/angular-training-slides#287]
- [ ] How do I run a test in Angular (10 minute)
    - the toolchain
    - running tests with the CLI and viewing output
    - creating new elements and running tests in watch mode with CLI
- [ ] How do I write tests (10 minutes)
    - Arrange, Act and Assert in Jasmine
    - describe, beforeEach, it, expect
- [ ] How do I test a pipe (10 minutes)
    - Instantiating the class in the beforeEach
    - running expect on the transform method
- [ ] How do I do an isolated test (10 minutes)
    - Instantiating the component or service
    - mocking dependencies
    - testing business logic
- [ ] How do I configure the testing module (15 minutes)
    - when to use TestBed
    - providing moc dependencies
    - injecting real providers and spying on their methods
    - importing real modules from the app
- [ ] How do I test a component using ComponentFixture (20 minutes)
    - debugElement, componentInstance, NativeElement
    - causing change detection, setting up automatic change detection
    - querying the native element
    - Overriding dependencies
- [ ] How do I deal with asynchronous behaviour in my tests (15 minutes)
    - running tests in a zone
    - async
    - fakeAsync and tick
- [ ] How do I test services (20 minutes)
    - mocking Angular’s Http services
    - what to test
    - create and inject the mock
    - creating new observables for mocks

~ 2 hours

**Comment by gvwilson** [comment]
See #293

**Comment by mdegani** [comment]
This checklist leaves out the section on overriding templates: https://github.com/rangle/angular-training-slides/blob/online-training/slides/src/content/unit-testing.md#overriding-dependencies-for-testing-33.
