### ISSUE TITLE
Show how to swap in different test result reporter

### ISSUE THREAD

**Issue by gvwilson** [rangle/angular-training-slides#299]

**Comment by sonukapoor** [comment]
@gvwilson Do you want an additional slide for this?

**Comment by sonukapoor** [comment]
BTW: This is the one I was referring to:

```
npm install karma-spec-reporter --save-dev
```

In the Karma.config change the reporters to:

```
reporters: ['spec']
```

**Comment by mdegani** [comment]
@gvwilson this is in the ready column, but is this something we really want to cover? karma-spec-reporter is likely nicer than what we get by default, but the one the cli gives us is not too bad. Maybe we put this in the notes and pull it out of our back pocket if the audience is interested in a tdd approach/workflow?

**Comment by gvwilson** [comment]
This one was Sonu's suggestion - I'm happy to defer to whatever you two
think is best.

**Comment by sonukapoor** [comment]
I find that the output generated by `karma-spec-reporter` is a lot cleaner than the one that comes by ng. 

ng test with the default reporter:

<img width="982" alt="screen shot 2017-05-01 at 9 21 58 am" src="https://cloud.githubusercontent.com/assets/59734/25580669/b64c1e68-2e50-11e7-98c5-3ad2ba6123f6.png">

ng test with the karma-spec reporter:

<img width="1004" alt="screen shot 2017-05-01 at 9 30 18 am" src="https://cloud.githubusercontent.com/assets/59734/25580688/d254c466-2e50-11e7-9601-4a3542f208f6.png">

**Comment by mdegani** [comment]
Yeah, it would be worth installing up front. Much better than switching to the browser to see details.
