### ISSUE TITLE
Where should we keep our sample code and how should we keep it up to date?

### ISSUE THREAD

**Issue by gvwilson** [rangle/angular-training-slides#324]
E.g., slide 39

**Comment by gvwilson** [comment]
- Should we use Plnkr (or something like it) at all?
- Should we host them ourselves?
- Who should own them?
- How will we keep them up to date?
- How will we accommodate the differences between Plnkr and Angular CLI apps?

**Comment by mdegani** [comment]
We could also consider [Glitch](https://glitch.com/). You can pull from github, thought I don't think you get git features after the code has been copied over. The code should not require systemjs, but instead run webpack as normal.

**Comment by gvwilson** [comment]
We need to make a decision about how to manage
the example code used in our lessons on Angular and React.
This issue lays out options that have been presented so far;
please critique them,
add others,
and lt us know what you think would work best.

**Requirements**

1.  *Base lessons on a single extended example.*
    -   Lessons for people who are already competent
        (i.e., who already have a mental model of the subject)
        can be a grab bag of references and unconnected examples.
    -   Lessons for novices (who are trying to build a mental model)
        should build a single extended example
        so that learners don't repeatedly have to handle
        the extra cognitive load of learning a new application
        as well as a new subject.

2.  *Share code with learners in class.*
    -   Learners who fall behind or have to miss part of a training
        need a way to re-synchronize.
    -   Learners sometimes also want a clean version
        of the code built in class
        for future reference.

3.  *Share code with current lesson co-authors.*
    -   People reviewing changes to teaching materials
        must be able to run the examples those materials describe
        to be sure that they work.

4.  *Share code with future lesson co-authors.*
    -   Someone who wants to fix or improve existing material
        should be able to start contributing with little or no startup effort.
    -   For example,
        if they want to add material on a topic that occurs mid-way through the lessons,
        it should not take them more than a few minutes
        to set up the example application
        in a state synchronzied with the start of that topic.

**Problems**

Imagine that we always taught exactly the same material
in exactly the same order,
and that our lessons never changed.
In that happy universe,
we would build an example application step by step,
committing each major change to a Git repo and tagging it.
Instructors would then recapitulate those steps
in class in a brand new repository,
committing as they went.

*   Learners could pull from the temporary in-class repository
    to catch up whenever they fell behind.
*   Authors could fork the reference repository
    and re-set to a tag to look at the application as it was
    at the start of some section of the lessons.

Unfortunately,
we don't live in that happy universe.
When someone fixes a bug or makes an improvement to some section of a lesson,
those changes have to propagate downstream,
which is a maintenance headache.

We discussed several possible solutions:

1.  *Use branches in a single repository.*
    The `master` branch of the repository would hold the common starting point for all lessons
    (e.g., the material usually covered in a fixed order on the first day).
    Every other topic would branch off `master`.
    -   Pro: we know how to manage software using Git.
    -   Pro: everything is in one findable place.
    -   Con: maintenance, maintenance, maintenance.
        Any change in an early part of a lesson has to be propagated to later parts.

2.  *Don't maintain the source code of the lesson at all.*
    Our example applications are pretty small;
    if someone can't re-create a particular snapshot of a lesson fairly quickly,
    they probably shouldn't be teaching the lesson.
    -   Pro: no maintenance!
    -   Con: extra (repeated) work for everyone
        who wants to make a non-trivial change to a lesson.

3.  *Create independent mini-examples.*
    Rather than having a reference repository with the example application,
    we could maintain a handful of completely independent mini-applications,
    each of which illustrates a single key idea.
    Authors would use and update these when fixing or updating lessons.
    In class,
    instructors would build a sample application
    that contains these ideas.
    -   Pro: lower maintenance cost.
    -   Pro: makes it easier to change topic order in lessons.
    -   Con: may not actually save us much maintenance.
        If, for example, someone makes a change to the mini-application illustrating Idea A,
        the mini-applications illustrating ideas that are usually taught later
        really ought to be updated.
    -   Con: more load on instructors,
        who need to be able to integrate ideas on the fly.
        -   Although the ideas being integrated would be fairly stable,
            so this isn't completely improvised.
    -   Con: no reference implementation of the entire application built in class.
        (Each training event would produce *some* application,
        but we wouldn't have a complete one that was guaranteed to be up to date.)

This is an intrinsically hard problem,
just like maintaining several parallel versions of a single application
to run on different platforms.
Please let us know what you think of these ideas,
and what other solutions might work better.

**Comment by AbdellaToronto** [comment]
It might help if we use an example of one of our own lessons and demo applications that have fallen into disrepair, and a post mortem might give us more insight into our own **specific** challenges with this problem. For example, maybe in this observation we notice that we have a particular hard time in Rangle maintaining out of date software because we are adherents of the bleeding edge, so maintaining any overly complex code base has an additional dimension of 'Well we don't really use generators anymore in favour of a more observable based asnyc management system' - as opposed to just the usual 'this library is now out of sync'.

Additionally, I think it might be helpful looking around at other companies and groups who are trying to do something similar - for example, Angular Academy - what's their current process? Do we have any insight into any challenges or pivots they've gone through?

**Comment by AbdellaToronto** [comment]
What went wrong with https://www.gitbook.com/book/rangle-io/react-training/details? We had something here for a while but it's now a year out of date. Why did we stop maintaining it, what were we using it for before?

**Comment by winkerVSbecks** [comment]
@AbdellaToronto with that one the code never worked out. We followed the gitbook and used it as a guide for live coding and some quick exercises. The other code branches were never used.

**Comment by winkerVSbecks** [comment]
@gvwilson my vote goes to "Use branches in a single repository" 🗳 
Not my favourite option but, probably the best option to scale the training.
