### ISSUE TITLE
Slide 113: correct description

### ISSUE THREAD

**Issue by gvwilson** [rangle/angular-training-slides#354]
- Creates test files for everything generated by angular cli rather than just components
- Find terminology for Angular declarations

**Comment by mdegani** [comment]
![image](https://cloud.githubusercontent.com/assets/5910433/25342481/2fb2857a-28da-11e7-8eed-1fdd4ee18aca.png)

**Comment by mdegani** [comment]
here is where I saw components, directives, pipes and services collectively referred to as "angular elements". If we can use this terminology, it helps to make our slides less wordy. This is from @barretodavid webinar in October.
