### ISSUE TITLE
Add content describing change detection

### ISSUE THREAD

**Issue by jamesbs** [rangle/angular-training-slides#367]
Slide 130: Testing makes a reference to change detection. This is necessary for testing components.
Determine what amount of content we want to add going over change detection

**Comment by mdegani** [comment]
In my PR for the testing slides redo  #496, `detectChanges()` is explained on one slide and then automatic change detection is explained on the next slide. I would hope that this is not too much information, but another option might be to remove the first slide and tell students to simply have angular automatically detect changes (one line of code for enter TestBed module) and not really explain why it is needed, other than it is needed for the component and template to sync up.

**Comment by gvwilson** [comment]
I like the description you have - let's revisit this after live training that uses this flow.
