### ISSUE TITLE
Uniquely identifying slides

### ISSUE THREAD

**Issue by jamesbs** [rangle/angular-training-slides#413]
We're currently using slide numbers to refer to slides, since content changes regularly, those numbers shift around too much to be reliable. Ideas so far:

- generate some hash when a new slide is created and persist that has for as long as that slide exists
- create a revealjs plugin to automate hash generation and assignment
- create some slide summary or unique title for each slide that isn't represented in presented content

**Comment by mdegani** [comment]
Per discussion yesterday: we will be using a slug to identify each slide. This will be synced with url using standard revealjs api.
