### ISSUE TITLE
Move dev-tools discussion earlier

### ISSUE THREAD

**Issue by mdegani** [rangle/angular-training-slides#430]
Slide 184: Move the section on dev tools earlier so students can use them to view their actions as they work with redux.

**Comment by sonukapoor** [comment]
@gvwilson This requires a little more work. For the redux tools to work, we need to call: `StoreDevtoolsModule.instrumentOnlyWithExtension({})` in `@NgModule`, which is in the middle of when we are updating our app to redux.

**Comment by sonukapoor** [comment]
Based of the discussion with @rpdasilva and @mdegani I will merge the redux section and redux tools sections together into one as this seems to give our users most of the value.
