### ISSUE TITLE
update issues that refer to slide id's

### ISSUE THREAD

**Issue by mdegani** [rangle/angular-training-slides#464]
Even if a slide has a custom id, the old numeric id can still be used in the url for navigation.

**Comment by mdegani** [comment]
@gvwilson should we prioritize this? To do this, we could paste new url's into remaining issues.

**Comment by gvwilson** [comment]
I'll take this one on - I figure it's pretty mechanical, and y'all should
focus on the content stuff that I don't know well enough to write.  I'll go
through them tonight - thanks.
- G
