### ISSUE TITLE
Setup CI Task to check duplicate slide IDs

### ISSUE THREAD

**Issue by sonukapoor** [rangle/angular-training-slides#471]

**Comment by mdegani** [comment]
@gvwilson do you want CI/CD set up as part of this issue? I.e. circle CI or other service that integrates with GitHub? Or is this issue more about having `npm start` simply fail when there are duplicate ID's?

**Comment by gvwilson** [comment]
Anything that integrates with GitHub so that we catch duplicate IDs when
people are trying to merge PRs - thanks.

**Comment by sonukapoor** [comment]
@gvwilson: 

CI has been setup. It will run whenever a PR is created or updated. It currently does not contain any tests for the duplicate ID check. That part is in a different PR (#506) and assigned to @mdegani.

**Comment by sonukapoor** [comment]
Connects to #513
