### ISSUE TITLE
Test whether extra nodes inserted by Angular mess up a11y

### ISSUE THREAD

**Issue by gvwilson** [rangle/angular-training-slides#526]
Check that Angular-generated DOM behaves as expected.

**Comment by neelghosh** [comment]
Greg, please remind me what this one is?  tks

**Comment by neelghosh** [comment]
Gentlemen I need to review with you.  Having some issues running voice over with the a11y code.  It might be the way I'm running it

**Comment by gvwilson** [comment]
Sure, I'll come find you as soon as I'm in today.  (At the dentist first
thing...)
