### ISSUE TITLE
Add example of skip to nav

### ISSUE THREAD

**Issue by gvwilson** [rangle/angular-training-slides#530]
Show people how this works (possibly an audio clip?)

**Comment by neelghosh** [comment]
I have created a separate screen recorded file showing a public gov't site with the functionality being played out.  This can be played to supplement the slides.

**Comment by gvwilson** [comment]
cool!

**Comment by gvwilson** [comment]
Can this one now be closed?

**Comment by neelghosh** [comment]
separate file will be created with JAWS walkthrough recorded - issue closed
