### ISSUE TITLE
Slide content being cut off

### ISSUE THREAD

**Issue by winkerVSbecks** [rangle/angular-training-slides#63]
Some slides have content that is too long for the slide container. It ends up being cut off. For example slide#21

![screen shot 2016-12-05 at 10 36 39 am](https://cloud.githubusercontent.com/assets/42671/20890945/d16c60e2-bad6-11e6-86fe-00ca4c5677ae.png)

Once I zoom out you can see that the example link was hidden

![screen shot 2016-12-05 at 10 36 42 am](https://cloud.githubusercontent.com/assets/42671/20890961/dd87896a-bad6-11e6-8f62-bae0c612ade3.png)

Reveal JS allows us to create nested slides which flow ↕️ and then the top level slides flow ⬅️➡️ as usual. Or just break them into multiple top level slides.

**Comment by ggprod** [comment]
resolved via PR72
