### ISSUE TITLE
Add slides for `$http`

### ISSUE THREAD

**Issue by winkerVSbecks** [rangle/angular-training-slides#66]
Generate a few slides using the content from gitbook: https://angular-2-training-book.rangle.io/handout/http/

**Comment by barretodavid** [comment]
I have updated the service section and added 2 slides for the $http service in this PR https://github.com/rangle/angular-training-slides/pull/73. I also created today a new PR for a plunker showing how to use it here https://github.com/rangle/angular-training-slides/pull/75

Do you have something else in mind for the section or should we close this issue?

**Comment by winkerVSbecks** [comment]
@barretodavid I was hoping to convert all of the `http` section to slides. Do you think that is overkill?

**Comment by barretodavid** [comment]
@winkerVSbecks makes sense, I'll work on that after the online training this week
