### ISSUE TITLE
Transform the routing exercise into the new format

### ISSUE THREAD

**Issue by barretodavid** [rangle/angular-training-slides#91]
We have an exercise for the route section using the old format [here](https://github.com/rangle/angular-training-slides/tree/master/exercises-old/routing/exercise). In my opinion this exercise is too complex to be able to finish in ~20 min. We should consider creating a simplified one or creating three independent exercises (basic, intermediate and advanced). Suggestions?

Remember to follow the exercise [guidelines](https://docs.google.com/document/d/1t2rLglPKLPEue-gJ2DAVefglbqr2g2daeHUbzqmWW2o/edit#heading=h.5btd8e1fv1jv)

**Comment by moarsel** [comment]
Hey @barretodavid, so I looked through the routing exercise and, like you said, it wouldn’t be easy to do in 20 minutes. Looking at the other exercises, they are more simple. 

Maybe we could cut out the child route stuff, but still keep the route parameter part (and maybe simplify it a bit more). I think if we did it this way and had step by step instructions then it would be much quicker to get through.

What do you think?

**Comment by barretodavid** [comment]
yes that makes sense to me. In the future if we need another more advanced exercise we can take a look again at the base example and create a more complex one. For one, simpler is better

**Comment by moarsel** [comment]
Ok great. So for this to be complete should I first create the new exercise in the solutions directory, write the new exercise readme, and create the new exercise (without the full solution)?

**Comment by barretodavid** [comment]
It's up to you, you can submit both in the same PR. I usually find helpful to do the exercise first and then write the instructions
