### ISSUE TITLE
Add slides for the `angular-cli`

### ISSUE THREAD

**Issue by barretodavid** [rangle/angular-training-slides#98]
This section should be the second module of the training right after the "Creating a Hello World Application"

**Comment by barretodavid** [comment]
This section should be the second module of the training right after the "Creating a Hello World Application"

**Comment by ShaunLloyd** [comment]
hey @barretodavid I can get this done today. 

I would assume you want the following slides:

- creating a new project (new vs init)
- generate component/directive/route/service/pipe
- ng test and ng e2e for testing

any other topics I missed you feel I should cover?

**Comment by barretodavid** [comment]
Yes, I think that's enough for people to do the exercises. It's a good idea to keep it simple
